### ISSUE TITLE
Delete applet raise error: RuntimeError: SW match failed! Expected 9000 and got 6a88.

### ISSUE THREAD

**Issue by liuwei-network** [herlesupreeth/sim-tools#1]
Hello,

Thanks for update this tool, I've install the helloSTK.cap sucessfully.
However, when I want to delete it, or install it again, it raise error:
```
Traceback (most recent call last):
  File "shadysim_isim.py", line 491, in <module>
    ac.delete_aid(args.delete_app)
  File "shadysim_isim.py", line 257, in delete_aid
    return self.send_wrapped_apdu_checksw(apdu)
  File "shadysim_isim.py", line 246, in send_wrapped_apdu_checksw
    raise RuntimeError("SW match failed! Expected %s and got %s." % (sw.lower(), response[1]))
RuntimeError: SW match failed! Expected 9000 and got 6a88.
```

My delete command is 
```
 python2 shadysim_isim.py  --pcsc  -d d07002CA449001 --kic KIC1 --kid KID1
```

Did you experience this issue?

When I try to install it again, it raise error:
```
Traceback (most recent call last):
  File "shadysim_isim.py", line 494, in <module>
    ac.load_app(args.load_app)
  File "shadysim_isim.py", line 369, in load_app
    self.load_aid_raw(aid, data, len(data) / 2)
  File "shadysim_isim.py", line 271, in load_aid_raw
    self.send_wrapped_apdu_checksw('80e60200' + ('%02x' % (len(data) / 2)) + data + '00c0000000')
  File "shadysim_isim.py", line 246, in send_wrapped_apdu_checksw
    raise RuntimeError("SW match failed! Expected %s and got %s." % (sw.lower(), response[1]))
RuntimeError: SW match failed! Expected 9000 and got 6985.
```

I'm using sysmoISIM-SJA2.

**Comment by herlesupreeth** [comment]
Hmm, the error code 6a88 corresponds to following message, so I am assuming when you try to delete the helloSTK you are providing incorrect module id.

![image](https://github.com/herlesupreeth/sim-tools/assets/4115839/aefbf51f-866a-4e21-a362-369d5cf4d269)

you could try the following

```
# List all the applets installed on the card
python2 shadysim_isim.py  --pcsc  -t

# then, execute the delete command using the module id of helloSTK applet printed out by above command

```
tbh, I have used only the --aram mode in the shadysim_isim script and nothing else so it could be possible that deletion is not working

**Comment by liuwei-network** [comment]
Thanks, it was my mistake to take `instance-aid` as `aid`, now I can delete it.
